// Package runner provides functionality to execute Go tests and parse their JSON output.
package runner

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/atendi9/capivara/langs"
)

const (
	iconError   = "🔥"
	iconFailPkg = "💥"
	iconPass    = "🚀"
	iconFail    = "☠️ "
)

// translations is the internal dictionary that maps output messages
// according to the configured language.
var translations = map[langs.Lang]map[string]string{
	langs.EN_US: {
		"err_capture": "Error capturing output:",
		"err_start":   "Error starting tests:",
		"pkg_fail":    "PACKAGE FAILED:",
		"success":     "[SUCCESS]",
		"fail":        "[FAILED]",
	},
	langs.PT_BR: {
		"err_capture": "Erro ao capturar saída:",
		"err_start":   "Erro ao iniciar testes:",
		"pkg_fail":    "PACOTE FALHOU:",
		"success":     "[SUCESSO]",
		"fail":        "[FALHOU]",
	},
}

// TestEvent represents the JSON generated by the `go test -json` command.
type TestEvent struct {
	Action  string  `json:"Action"`  // run, pass, fail, output, skip
	Package string  `json:"Package"` // Package name
	Test    string  `json:"Test"`    // Test name (empty if it's a package-level event)
	Output  string  `json:"Output"`  // The printed text
	Elapsed float64 `json:"Elapsed"` // Time elapsed (in seconds)
}

// Exec defines the interface for command execution.
type Exec interface {
	StdoutPipe() (io.ReadCloser, error)
	Start() error
	Wait() error
}

// CommandFn defines a function signature for creating a new command execution.
type CommandFn func(cmd string, args ...string) Exec

// Runner holds the state of the test runner, including the selected
// language for console output and the command execution function.
type Runner struct {
	lang langs.Lang
	fn   CommandFn
}

// New initializes a new test Runner instance.
func New(lang langs.Lang, fn CommandFn) *Runner {
	return &Runner{lang: lang, fn: fn}
}

// Execute runs the go test command with JSON output and parses the stream.
func (r *Runner) Execute() {
	args := append([]string{"test", "-json"}, os.Args[1:]...)
	cmd := r.fn("go", args...)

	stdout, err := cmd.StdoutPipe()
	if err != nil {
		fmt.Printf("%s %s %v\n", iconError, translate(r.lang, "err_capture"), err)
		os.Exit(1)
	}

	if err := cmd.Start(); err != nil {
		fmt.Printf("%s %s %v\n", iconError, translate(r.lang, "err_start"), err)
		os.Exit(1)
	}

	scanner := bufio.NewScanner(stdout)
	for scanner.Scan() {
		line := scanner.Text()

		var event TestEvent
		if err := json.Unmarshal([]byte(line), &event); err != nil {
			fmt.Println(line)
			continue
		}

		r.processEvent(event)
	}

	err = cmd.Wait()
	if err != nil {
		os.Exit(1)
	}
}

// processEvent handles individual test events and formats the console output based on the action.
func (r *Runner) processEvent(e TestEvent) {
    if e.Test == "" {
        if e.Action == "fail" {
            fmt.Printf("\n%s %s %s\n", iconFailPkg, translate(r.lang, "pkg_fail"), e.Package)
        }
        return
    }

    switch e.Action {
    case "output":
        text := e.Output
    
        trimmedText := strings.TrimSpace(text)
        
        if strings.HasPrefix(trimmedText, "=== RUN") ||
            strings.HasPrefix(trimmedText, "--- PASS") ||
            strings.HasPrefix(trimmedText, "--- FAIL") {
            return
        }

        fmt.Print(strings.TrimRight(text, "\n"))
        fmt.Println()

    case "pass":
        fmt.Printf("\n%s %s %s (%.2fs)\n", iconPass, translate(r.lang, "success"), e.Test, e.Elapsed)
        fmt.Println("--------------------------------------------------")

    case "fail":
        fmt.Printf("\n%s %s %s (%.2fs)\n", iconFail, translate(r.lang, "fail"), e.Test, e.Elapsed)
        fmt.Println("--------------------------------------------------")
    }
}

// translate is an internal helper function that fetches the localized text.
func translate(lang langs.Lang, key string) string {
	if langMap, ok := translations[lang]; ok {
		if msg, exists := langMap[key]; exists {
			return msg
		}
	}
	// Safety fallback to English
	return translations[langs.EN_US][key]
}